lang = "en"
host = "releases.uwe.app"

[dependencies."std::core"]
version = "~4.1.6"
apply = { styles = ["**"] }

[page.meta]
description = "UWE software releases"
keywords = "Web Editor, Release, Software"

[db.load.releases]
type = "json"
provider = "files"
from = "collections/releases"

[db.load.releases.on.all]
key = "*"

[pages."index.md".query]
name = "releases"
index = "all"
include-docs = true

[publish.aws]
region = "ap-southeast-1"
credentials = "uwe"

[publish.aws.environments.production]
bucket = "releases.uwe.app"
keep-remote = true
