lang = "en"
host = "releases.uwe.app"

[dependencies."std::core"]
version = "~4.1.6"
apply = { styles = ["**"] }

[page.meta]
description = "UWE software releases"
keywords = "Web Editor, Release, Software"

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"

[publish.aws.environments.production]
bucket = "releases.uwe.app"
