lang = "en"
host = "localhost"
[dependencies."std::core"]
version = "~4.1.6"

[dependencies."std::core".apply]
styles = ["**"]
[page.meta]
description = "Website"
keywords = "Vanilla, Website"

[fluent]
fallback = "en"
shared = "core.ftl"
